baseURL = "http://swanav.github.io/zeus"
languageCode = "en-us"
publishDir = "../public"
title = "Zeus"
theme = "kube"

Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Zeus" # add your company name
  github = "swanav/zeus" # add your github profile name
  email = "sswanav@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Diary"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
